import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "./QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
  openGraph:{
    title: "Home",
    description: "A Next.js app with TanStack Query",
    siteName: "Next.js app" ,
    images:"https://i0.wp.com/frontendmasters.com/blog/wp-content/uploads/2024/09/m_Vw7t19_400x400.jpg?fit=400%2C400&ssl=1",
    locale: "en_US",
    type: "website",
  }

};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
